# Generated by Django 6.1.1 on 2026-09-20 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hello', '0002_profile_description_experience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=70, null=True)),
                ('location', models.CharField(max_length=70, null=True)),
                ('duration', models.CharField(max_length=70, null=True)),
                ('degree', models.CharField(max_length=70, null=True)),
                ('study_discription', models.CharField(max_length=70, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
