# Generated by Django 6.1.1 on 2026-09-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hello', '0003_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('diploma', 'Diploma'), ('associate', 'Asociate deegree'), ('bachelor', "Bachelor's degree"), ('master', "Master's degree"), ('phd', 'Phd')], max_length=70, null=True),
        ),
    ]
